kind: pipeline
name: blog

volumes:
  - name: cache
    host:
      path: /tmp/cache

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules

  - name: install
    image: node:18.6.0-alpine
    commands:
      - npm install

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules

  - name: build
    image: node:18.6.0-alpine
    commands:
      - npm run build

  - name: github-pages  
    image: plugins/gh-pages
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_password
      pages_directory: public/

  - name: notify
    image: drillster/drone-email
    settings:
      host:
        from_secret: smtp_host #  smtp.qq.com
      port:
        from_secret: smtp_port #  465
      username:
        from_secret: smtp_username #  邮箱用户名
      password:
        from_secret: smtp_password #  邮箱密码
      from:
        from_secret: smtp_from #  发送人
      recipients:
        from_secret: smtp_recipients #  收件人 xx,xx
    when: #执行条件
      status:
        - success
        - changed
        - failure